services:
  - type: web
    name: project-management-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://madhurimallipudi6_db_user:anu%4087477@cluster0.so61gxy.mongodb.net/projectmanagement?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
